### ISSUE TITLE
fg.screen_scale just does nothing

### ISSUE THREAD

**Issue by nodepond** [adonaac/fuccboiGDX#33]
There are still issues in the camera-system. Just like the documentation warns that "Resizing and scaling the screen may cause unexpected bugs with cameras if the zoom calls are used with the engine. Try to use fg.screen_scale instead."

I did try to set the fg.screen_scale to 1, 4 or -4 and it does not change anything on the scale. This is also true for the 2d platformer example in the advanced tutorials.

**Comment by adonaac** [comment]
The way this works is that everything is draw to a canvas at the smallest resolution, which is by default 480x360 I think. If you do fg.screen_scale = 2, then it just draws this 480x360 canvas scaled by 2. If you do fg.screen_scale = 2 and fg.setScreenSize(960, 720), for example, you should effectively just have your game scaled by 2.

**Comment by nodepond** [comment]
Aha. It seems, that the order of making the calls is important!
Works:

    fg.setScreenSize(960, 720)
    fg.screen_scale = 4

Changing screen_scale params doesn't change anything:

    fg.screen_scale = 4
    fg.setScreenSize(960, 720)

Could be fixed in the tutorial file.

**Comment by adonaac** [comment]
Yea I forgot, fg.screen_scale simply scales the canvas (and it should work by itself as a camera zoom sort of), and fg.setScreenSize scales the canvas (figures out fg.screen_scale automatically) and also changes the screen size. On the 2D Platformer tutorial, using only fg.screen_scale = 2 works, but you remain with a 480x360 screen, and using fg.setScreenSize changes the screen size as well as the screen scale. 

In your first example you double the screen size and double the scale but then you make the scale 4, which gives you the same result as if you just doubled the scale but not the screen, just on a bigger screen. On your second example you set the screen scale but right after you set it again automatically via the fg.setScreenSize call, along with the screen size.
